# Generated by Django 4.2.4 on 2023-11-23 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_file_name', models.CharField(max_length=255)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('upload_status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('incomplete', 'Incomplete')], max_length=20)),
                ('meta_data', models.TextField(null=True)),
                ('remarks', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(null=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PdfDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_number', models.IntegerField()),
                ('image', models.BinaryField()),
                ('text', models.TextField()),
                ('meta_data', models.TextField(null=True)),
                ('remarks', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(null=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('pdf_file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocrapi.pdffiles')),
            ],
        ),
    ]
