# Generated by Django 4.2.4 on 2023-12-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdetails',
            name='image',
        ),
        migrations.AddField(
            model_name='pdfdetails',
            name='image_location',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pdffiles',
            name='file_location',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
