# Generated by Django 4.2.4 on 2023-12-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapi', '0002_remove_pdfdetails_image_pdfdetails_image_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffiles',
            name='total_page',
            field=models.IntegerField(null=True),
        ),
    ]
