# Generated by Django 4.2.4 on 2023-12-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapi', '0003_pdffiles_total_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffiles',
            name='total_size',
            field=models.IntegerField(null=True),
        ),
    ]
