# Generated by Django 4.2.4 on 2023-12-26 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapi', '0008_alter_pdffiles_uploaded_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdffiles',
            old_name='upload_status',
            new_name='extraction_status',
        ),
    ]
