# Generated by Django 4.2.4 on 2023-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_id',
            field=models.CharField(default=models.EmailField(max_length=255, unique=True, verbose_name='Email'), max_length=255, null=True),
        ),
    ]
